//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StayBazar.BookingServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CartItemByID", Namespace="http://schemas.datacontract.org/2004/07/TamarindXML.BusinessClass")]
    [System.SerializableAttribute()]
    public partial class CartItemByID : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CartItemIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CartItemID {
            get {
                return this.CartItemIDField;
            }
            set {
                if ((this.CartItemIDField.Equals(value) != true)) {
                    this.CartItemIDField = value;
                    this.RaisePropertyChanged("CartItemID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InputException", Namespace="http://schemas.datacontract.org/2004/07/TamarindXML.BusinessClass")]
    [System.SerializableAttribute()]
    public partial class InputException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InnerExceptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionMessage {
            get {
                return this.ExceptionMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionMessageField, value) != true)) {
                    this.ExceptionMessageField = value;
                    this.RaisePropertyChanged("ExceptionMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InnerException {
            get {
                return this.InnerExceptionField;
            }
            set {
                if ((object.ReferenceEquals(this.InnerExceptionField, value) != true)) {
                    this.InnerExceptionField = value;
                    this.RaisePropertyChanged("InnerException");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CartItem", Namespace="http://schemas.datacontract.org/2004/07/TamarindXML.BusinessClass")]
    [System.SerializableAttribute()]
    public partial class CartItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AllowOnrequestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BreakFastField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CartIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CartItemIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CheckInDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DinnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DoubleRoomsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExtraBedsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StayBazar.BookingServiceRef.CartFlightDetails FlightDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal GSTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HotelIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HotelRateCartDetailIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool LunchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NoOfNightsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginCountryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StayBazar.BookingServiceRef.CartPaxDetails[] PassengersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoomCategoryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SingleRoomsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TwinRoomsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowOnrequest {
            get {
                return this.AllowOnrequestField;
            }
            set {
                if ((this.AllowOnrequestField.Equals(value) != true)) {
                    this.AllowOnrequestField = value;
                    this.RaisePropertyChanged("AllowOnrequest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BreakFast {
            get {
                return this.BreakFastField;
            }
            set {
                if ((this.BreakFastField.Equals(value) != true)) {
                    this.BreakFastField = value;
                    this.RaisePropertyChanged("BreakFast");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CartID {
            get {
                return this.CartIDField;
            }
            set {
                if ((this.CartIDField.Equals(value) != true)) {
                    this.CartIDField = value;
                    this.RaisePropertyChanged("CartID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CartItemID {
            get {
                return this.CartItemIDField;
            }
            set {
                if ((this.CartItemIDField.Equals(value) != true)) {
                    this.CartItemIDField = value;
                    this.RaisePropertyChanged("CartItemID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CheckInDate {
            get {
                return this.CheckInDateField;
            }
            set {
                if ((this.CheckInDateField.Equals(value) != true)) {
                    this.CheckInDateField = value;
                    this.RaisePropertyChanged("CheckInDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityID {
            get {
                return this.CityIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CityIDField, value) != true)) {
                    this.CityIDField = value;
                    this.RaisePropertyChanged("CityID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Dinner {
            get {
                return this.DinnerField;
            }
            set {
                if ((this.DinnerField.Equals(value) != true)) {
                    this.DinnerField = value;
                    this.RaisePropertyChanged("Dinner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DoubleRooms {
            get {
                return this.DoubleRoomsField;
            }
            set {
                if ((this.DoubleRoomsField.Equals(value) != true)) {
                    this.DoubleRoomsField = value;
                    this.RaisePropertyChanged("DoubleRooms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExtraBeds {
            get {
                return this.ExtraBedsField;
            }
            set {
                if ((this.ExtraBedsField.Equals(value) != true)) {
                    this.ExtraBedsField = value;
                    this.RaisePropertyChanged("ExtraBeds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StayBazar.BookingServiceRef.CartFlightDetails FlightDetails {
            get {
                return this.FlightDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.FlightDetailsField, value) != true)) {
                    this.FlightDetailsField = value;
                    this.RaisePropertyChanged("FlightDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal GST {
            get {
                return this.GSTField;
            }
            set {
                if ((this.GSTField.Equals(value) != true)) {
                    this.GSTField = value;
                    this.RaisePropertyChanged("GST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HotelID {
            get {
                return this.HotelIDField;
            }
            set {
                if ((this.HotelIDField.Equals(value) != true)) {
                    this.HotelIDField = value;
                    this.RaisePropertyChanged("HotelID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HotelRateCartDetailID {
            get {
                return this.HotelRateCartDetailIDField;
            }
            set {
                if ((object.ReferenceEquals(this.HotelRateCartDetailIDField, value) != true)) {
                    this.HotelRateCartDetailIDField = value;
                    this.RaisePropertyChanged("HotelRateCartDetailID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Lunch {
            get {
                return this.LunchField;
            }
            set {
                if ((this.LunchField.Equals(value) != true)) {
                    this.LunchField = value;
                    this.RaisePropertyChanged("Lunch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NoOfNights {
            get {
                return this.NoOfNightsField;
            }
            set {
                if ((this.NoOfNightsField.Equals(value) != true)) {
                    this.NoOfNightsField = value;
                    this.RaisePropertyChanged("NoOfNights");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginCountryID {
            get {
                return this.OriginCountryIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginCountryIDField, value) != true)) {
                    this.OriginCountryIDField = value;
                    this.RaisePropertyChanged("OriginCountryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StayBazar.BookingServiceRef.CartPaxDetails[] Passengers {
            get {
                return this.PassengersField;
            }
            set {
                if ((object.ReferenceEquals(this.PassengersField, value) != true)) {
                    this.PassengersField = value;
                    this.RaisePropertyChanged("Passengers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RoomCategoryID {
            get {
                return this.RoomCategoryIDField;
            }
            set {
                if ((this.RoomCategoryIDField.Equals(value) != true)) {
                    this.RoomCategoryIDField = value;
                    this.RaisePropertyChanged("RoomCategoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SingleRooms {
            get {
                return this.SingleRoomsField;
            }
            set {
                if ((this.SingleRoomsField.Equals(value) != true)) {
                    this.SingleRoomsField = value;
                    this.RaisePropertyChanged("SingleRooms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TwinRooms {
            get {
                return this.TwinRoomsField;
            }
            set {
                if ((this.TwinRoomsField.Equals(value) != true)) {
                    this.TwinRoomsField = value;
                    this.RaisePropertyChanged("TwinRooms");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CartFlightDetails", Namespace="http://schemas.datacontract.org/2004/07/TamarindXML.BusinessClass")]
    [System.SerializableAttribute()]
    public partial class CartFlightDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ArrivalDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArriveByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArriveCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArriveTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CartItemIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartureCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DepartureDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartureTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InstructionsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ArrivalDate {
            get {
                return this.ArrivalDateField;
            }
            set {
                if ((this.ArrivalDateField.Equals(value) != true)) {
                    this.ArrivalDateField = value;
                    this.RaisePropertyChanged("ArrivalDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArriveBy {
            get {
                return this.ArriveByField;
            }
            set {
                if ((object.ReferenceEquals(this.ArriveByField, value) != true)) {
                    this.ArriveByField = value;
                    this.RaisePropertyChanged("ArriveBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArriveCity {
            get {
                return this.ArriveCityField;
            }
            set {
                if ((object.ReferenceEquals(this.ArriveCityField, value) != true)) {
                    this.ArriveCityField = value;
                    this.RaisePropertyChanged("ArriveCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArriveTime {
            get {
                return this.ArriveTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.ArriveTimeField, value) != true)) {
                    this.ArriveTimeField = value;
                    this.RaisePropertyChanged("ArriveTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CartItemID {
            get {
                return this.CartItemIDField;
            }
            set {
                if ((this.CartItemIDField.Equals(value) != true)) {
                    this.CartItemIDField = value;
                    this.RaisePropertyChanged("CartItemID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartBy {
            get {
                return this.DepartByField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartByField, value) != true)) {
                    this.DepartByField = value;
                    this.RaisePropertyChanged("DepartBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartureCity {
            get {
                return this.DepartureCityField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartureCityField, value) != true)) {
                    this.DepartureCityField = value;
                    this.RaisePropertyChanged("DepartureCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DepartureDate {
            get {
                return this.DepartureDateField;
            }
            set {
                if ((this.DepartureDateField.Equals(value) != true)) {
                    this.DepartureDateField = value;
                    this.RaisePropertyChanged("DepartureDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartureTime {
            get {
                return this.DepartureTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartureTimeField, value) != true)) {
                    this.DepartureTimeField = value;
                    this.RaisePropertyChanged("DepartureTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Instructions {
            get {
                return this.InstructionsField;
            }
            set {
                if ((object.ReferenceEquals(this.InstructionsField, value) != true)) {
                    this.InstructionsField = value;
                    this.RaisePropertyChanged("Instructions");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CartPaxDetails", Namespace="http://schemas.datacontract.org/2004/07/TamarindXML.BusinessClass")]
    [System.SerializableAttribute()]
    public partial class CartPaxDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CartItemIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool LeadNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaxFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PaxIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaxLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaxSalutationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CartItemID {
            get {
                return this.CartItemIDField;
            }
            set {
                if ((this.CartItemIDField.Equals(value) != true)) {
                    this.CartItemIDField = value;
                    this.RaisePropertyChanged("CartItemID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool LeadName {
            get {
                return this.LeadNameField;
            }
            set {
                if ((this.LeadNameField.Equals(value) != true)) {
                    this.LeadNameField = value;
                    this.RaisePropertyChanged("LeadName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaxFirstName {
            get {
                return this.PaxFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PaxFirstNameField, value) != true)) {
                    this.PaxFirstNameField = value;
                    this.RaisePropertyChanged("PaxFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PaxID {
            get {
                return this.PaxIDField;
            }
            set {
                if ((this.PaxIDField.Equals(value) != true)) {
                    this.PaxIDField = value;
                    this.RaisePropertyChanged("PaxID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaxLastName {
            get {
                return this.PaxLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PaxLastNameField, value) != true)) {
                    this.PaxLastNameField = value;
                    this.RaisePropertyChanged("PaxLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaxSalutation {
            get {
                return this.PaxSalutationField;
            }
            set {
                if ((object.ReferenceEquals(this.PaxSalutationField, value) != true)) {
                    this.PaxSalutationField = value;
                    this.RaisePropertyChanged("PaxSalutation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoomType {
            get {
                return this.RoomTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomTypeField, value) != true)) {
                    this.RoomTypeField = value;
                    this.RaisePropertyChanged("RoomType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CartItemToDelete", Namespace="http://schemas.datacontract.org/2004/07/TamarindXML.BusinessClass")]
    [System.SerializableAttribute()]
    public partial class CartItemToDelete : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CartIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CartItemIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CartID {
            get {
                return this.CartIDField;
            }
            set {
                if ((this.CartIDField.Equals(value) != true)) {
                    this.CartIDField = value;
                    this.RaisePropertyChanged("CartID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CartItemID {
            get {
                return this.CartItemIDField;
            }
            set {
                if ((this.CartItemIDField.Equals(value) != true)) {
                    this.CartItemIDField = value;
                    this.RaisePropertyChanged("CartItemID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetailedCart", Namespace="http://schemas.datacontract.org/2004/07/TamarindXML.BusinessClass")]
    [System.SerializableAttribute()]
    public partial class DetailedCart : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CartIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CartID {
            get {
                return this.CartIDField;
            }
            set {
                if ((this.CartIDField.Equals(value) != true)) {
                    this.CartIDField = value;
                    this.RaisePropertyChanged("CartID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CartPolicies", Namespace="http://schemas.datacontract.org/2004/07/TamarindXML.BusinessClass")]
    [System.SerializableAttribute()]
    public partial class CartPolicies : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CancellationDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CartItemIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CheckInDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RateCardDetailsIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CancellationDetails {
            get {
                return this.CancellationDetailsField;
            }
            set {
                if ((this.CancellationDetailsField.Equals(value) != true)) {
                    this.CancellationDetailsField = value;
                    this.RaisePropertyChanged("CancellationDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CartItemID {
            get {
                return this.CartItemIDField;
            }
            set {
                if ((this.CartItemIDField.Equals(value) != true)) {
                    this.CartItemIDField = value;
                    this.RaisePropertyChanged("CartItemID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CheckInDate {
            get {
                return this.CheckInDateField;
            }
            set {
                if ((this.CheckInDateField.Equals(value) != true)) {
                    this.CheckInDateField = value;
                    this.RaisePropertyChanged("CheckInDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RateCardDetailsID {
            get {
                return this.RateCardDetailsIDField;
            }
            set {
                if ((object.ReferenceEquals(this.RateCardDetailsIDField, value) != true)) {
                    this.RateCardDetailsIDField = value;
                    this.RaisePropertyChanged("RateCardDetailsID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cart", Namespace="http://schemas.datacontract.org/2004/07/TamarindXML.BusinessClass")]
    [System.SerializableAttribute()]
    public partial class Cart : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CartIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CartID {
            get {
                return this.CartIDField;
            }
            set {
                if ((this.CartIDField.Equals(value) != true)) {
                    this.CartIDField = value;
                    this.RaisePropertyChanged("CartID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CartItemReferencePolicy", Namespace="http://schemas.datacontract.org/2004/07/TamarindXML.BusinessClass")]
    [System.SerializableAttribute()]
    public partial class CartItemReferencePolicy : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CartIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CartItemIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsRuleAcceptedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CartID {
            get {
                return this.CartIDField;
            }
            set {
                if ((this.CartIDField.Equals(value) != true)) {
                    this.CartIDField = value;
                    this.RaisePropertyChanged("CartID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CartItemID {
            get {
                return this.CartItemIDField;
            }
            set {
                if ((this.CartItemIDField.Equals(value) != true)) {
                    this.CartItemIDField = value;
                    this.RaisePropertyChanged("CartItemID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsRuleAccepted {
            get {
                return this.IsRuleAcceptedField;
            }
            set {
                if ((this.IsRuleAcceptedField.Equals(value) != true)) {
                    this.IsRuleAcceptedField = value;
                    this.RaisePropertyChanged("IsRuleAccepted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenceNo {
            get {
                return this.ReferenceNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceNoField, value) != true)) {
                    this.ReferenceNoField = value;
                    this.RaisePropertyChanged("ReferenceNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Quotation", Namespace="http://schemas.datacontract.org/2004/07/TamarindXML.BusinessClass")]
    [System.SerializableAttribute()]
    public partial class Quotation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CancellationDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuotationIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CancellationDetails {
            get {
                return this.CancellationDetailsField;
            }
            set {
                if ((this.CancellationDetailsField.Equals(value) != true)) {
                    this.CancellationDetailsField = value;
                    this.RaisePropertyChanged("CancellationDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QuotationID {
            get {
                return this.QuotationIDField;
            }
            set {
                if ((this.QuotationIDField.Equals(value) != true)) {
                    this.QuotationIDField = value;
                    this.RaisePropertyChanged("QuotationID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookingList", Namespace="http://schemas.datacontract.org/2004/07/TamarindXML.BusinessClass")]
    [System.SerializableAttribute()]
    public partial class BookingList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BookingNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CheckInDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CheckOutDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PassengerNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BookingNo {
            get {
                return this.BookingNoField;
            }
            set {
                if ((object.ReferenceEquals(this.BookingNoField, value) != true)) {
                    this.BookingNoField = value;
                    this.RaisePropertyChanged("BookingNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CheckInDate {
            get {
                return this.CheckInDateField;
            }
            set {
                if ((this.CheckInDateField.Equals(value) != true)) {
                    this.CheckInDateField = value;
                    this.RaisePropertyChanged("CheckInDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CheckOutDate {
            get {
                return this.CheckOutDateField;
            }
            set {
                if ((this.CheckOutDateField.Equals(value) != true)) {
                    this.CheckOutDateField = value;
                    this.RaisePropertyChanged("CheckOutDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassengerName {
            get {
                return this.PassengerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PassengerNameField, value) != true)) {
                    this.PassengerNameField = value;
                    this.RaisePropertyChanged("PassengerName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookingDetails", Namespace="http://schemas.datacontract.org/2004/07/TamarindXML.BusinessClass")]
    [System.SerializableAttribute()]
    public partial class BookingDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuotationIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuotationID {
            get {
                return this.QuotationIDField;
            }
            set {
                if ((object.ReferenceEquals(this.QuotationIDField, value) != true)) {
                    this.QuotationIDField = value;
                    this.RaisePropertyChanged("QuotationID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="www.tamarindtours.in/IBookingService", ConfigurationName="BookingServiceRef.IBookingService")]
    public interface IBookingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/IBookingService/IBookingService/GetCartItemDetailsByCartItem" +
            "ID", ReplyAction="www.tamarindtours.in/IBookingService/IBookingService/GetCartItemDetailsByCartItem" +
            "IDResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(StayBazar.BookingServiceRef.InputException), Action="www.tamarindtours.in/IBookingService/IBookingService/GetCartItemDetailsByCartItem" +
            "IDInputExceptionFault", Name="InputException", Namespace="http://schemas.datacontract.org/2004/07/TamarindXML.BusinessClass")]
        string GetCartItemDetailsByCartItemID(StayBazar.BookingServiceRef.CartItemByID cartItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/IBookingService/IBookingService/GetCartItemDetailsByCartItem" +
            "ID", ReplyAction="www.tamarindtours.in/IBookingService/IBookingService/GetCartItemDetailsByCartItem" +
            "IDResponse")]
        System.Threading.Tasks.Task<string> GetCartItemDetailsByCartItemIDAsync(StayBazar.BookingServiceRef.CartItemByID cartItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/IBookingService/IBookingService/InsertCartItem", ReplyAction="www.tamarindtours.in/IBookingService/IBookingService/InsertCartItemResponse")]
        string InsertCartItem(StayBazar.BookingServiceRef.CartItem cartItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/IBookingService/IBookingService/InsertCartItem", ReplyAction="www.tamarindtours.in/IBookingService/IBookingService/InsertCartItemResponse")]
        System.Threading.Tasks.Task<string> InsertCartItemAsync(StayBazar.BookingServiceRef.CartItem cartItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/IBookingService/IBookingService/RemoveFromCart", ReplyAction="www.tamarindtours.in/IBookingService/IBookingService/RemoveFromCartResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(StayBazar.BookingServiceRef.InputException), Action="www.tamarindtours.in/IBookingService/IBookingService/RemoveFromCartInputException" +
            "Fault", Name="InputException", Namespace="http://schemas.datacontract.org/2004/07/TamarindXML.BusinessClass")]
        string RemoveFromCart(StayBazar.BookingServiceRef.CartItemToDelete cartItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/IBookingService/IBookingService/RemoveFromCart", ReplyAction="www.tamarindtours.in/IBookingService/IBookingService/RemoveFromCartResponse")]
        System.Threading.Tasks.Task<string> RemoveFromCartAsync(StayBazar.BookingServiceRef.CartItemToDelete cartItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/IBookingService/IBookingService/GetCartDetails", ReplyAction="www.tamarindtours.in/IBookingService/IBookingService/GetCartDetailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(StayBazar.BookingServiceRef.InputException), Action="www.tamarindtours.in/IBookingService/IBookingService/GetCartDetailsInputException" +
            "Fault", Name="InputException", Namespace="http://schemas.datacontract.org/2004/07/TamarindXML.BusinessClass")]
        string GetCartDetails(StayBazar.BookingServiceRef.DetailedCart cart);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/IBookingService/IBookingService/GetCartDetails", ReplyAction="www.tamarindtours.in/IBookingService/IBookingService/GetCartDetailsResponse")]
        System.Threading.Tasks.Task<string> GetCartDetailsAsync(StayBazar.BookingServiceRef.DetailedCart cart);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/IBookingService/IBookingService/GetBookedCartDetails", ReplyAction="www.tamarindtours.in/IBookingService/IBookingService/GetBookedCartDetailsResponse" +
            "")]
        string GetBookedCartDetails(StayBazar.BookingServiceRef.DetailedCart Cart);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/IBookingService/IBookingService/GetBookedCartDetails", ReplyAction="www.tamarindtours.in/IBookingService/IBookingService/GetBookedCartDetailsResponse" +
            "")]
        System.Threading.Tasks.Task<string> GetBookedCartDetailsAsync(StayBazar.BookingServiceRef.DetailedCart Cart);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/IBookingService/IBookingService/GetSalutations", ReplyAction="www.tamarindtours.in/IBookingService/IBookingService/GetSalutationsResponse")]
        string GetSalutations();
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/IBookingService/IBookingService/GetSalutations", ReplyAction="www.tamarindtours.in/IBookingService/IBookingService/GetSalutationsResponse")]
        System.Threading.Tasks.Task<string> GetSalutationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/IBookingService/IBookingService/GetPolicies", ReplyAction="www.tamarindtours.in/IBookingService/IBookingService/GetPoliciesResponse")]
        string GetPolicies(StayBazar.BookingServiceRef.CartPolicies policy);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/IBookingService/IBookingService/GetPolicies", ReplyAction="www.tamarindtours.in/IBookingService/IBookingService/GetPoliciesResponse")]
        System.Threading.Tasks.Task<string> GetPoliciesAsync(StayBazar.BookingServiceRef.CartPolicies policy);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/IBookingService/IBookingService/ConfirmBooking", ReplyAction="www.tamarindtours.in/IBookingService/IBookingService/ConfirmBookingResponse")]
        string ConfirmBooking(StayBazar.BookingServiceRef.Cart cart, StayBazar.BookingServiceRef.CartItemReferencePolicy[] CartItemRef);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/IBookingService/IBookingService/ConfirmBooking", ReplyAction="www.tamarindtours.in/IBookingService/IBookingService/ConfirmBookingResponse")]
        System.Threading.Tasks.Task<string> ConfirmBookingAsync(StayBazar.BookingServiceRef.Cart cart, StayBazar.BookingServiceRef.CartItemReferencePolicy[] CartItemRef);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/IBookingService/IBookingService/RejectApproval", ReplyAction="www.tamarindtours.in/IBookingService/IBookingService/RejectApprovalResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(StayBazar.BookingServiceRef.InputException), Action="www.tamarindtours.in/IBookingService/IBookingService/RejectApprovalInputException" +
            "Fault", Name="InputException", Namespace="http://schemas.datacontract.org/2004/07/TamarindXML.BusinessClass")]
        string RejectApproval(StayBazar.BookingServiceRef.Quotation quot);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/IBookingService/IBookingService/RejectApproval", ReplyAction="www.tamarindtours.in/IBookingService/IBookingService/RejectApprovalResponse")]
        System.Threading.Tasks.Task<string> RejectApprovalAsync(StayBazar.BookingServiceRef.Quotation quot);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/IBookingService/IBookingService/AcceptApproval", ReplyAction="www.tamarindtours.in/IBookingService/IBookingService/AcceptApprovalResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(StayBazar.BookingServiceRef.InputException), Action="www.tamarindtours.in/IBookingService/IBookingService/AcceptApprovalInputException" +
            "Fault", Name="InputException", Namespace="http://schemas.datacontract.org/2004/07/TamarindXML.BusinessClass")]
        string AcceptApproval(StayBazar.BookingServiceRef.Quotation quot);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/IBookingService/IBookingService/AcceptApproval", ReplyAction="www.tamarindtours.in/IBookingService/IBookingService/AcceptApprovalResponse")]
        System.Threading.Tasks.Task<string> AcceptApprovalAsync(StayBazar.BookingServiceRef.Quotation quot);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/IBookingService/IBookingService/GetAmendBookingDetailsbyCart" +
            "ItemID", ReplyAction="www.tamarindtours.in/IBookingService/IBookingService/GetAmendBookingDetailsbyCart" +
            "ItemIDResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(StayBazar.BookingServiceRef.InputException), Action="www.tamarindtours.in/IBookingService/IBookingService/GetAmendBookingDetailsbyCart" +
            "ItemIDInputExceptionFault", Name="InputException", Namespace="http://schemas.datacontract.org/2004/07/TamarindXML.BusinessClass")]
        string GetAmendBookingDetailsbyCartItemID(StayBazar.BookingServiceRef.CartItemByID cart);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/IBookingService/IBookingService/GetAmendBookingDetailsbyCart" +
            "ItemID", ReplyAction="www.tamarindtours.in/IBookingService/IBookingService/GetAmendBookingDetailsbyCart" +
            "ItemIDResponse")]
        System.Threading.Tasks.Task<string> GetAmendBookingDetailsbyCartItemIDAsync(StayBazar.BookingServiceRef.CartItemByID cart);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/IBookingService/IBookingService/GetFlightAndOtherDetailsbyCa" +
            "rtItemID", ReplyAction="www.tamarindtours.in/IBookingService/IBookingService/GetFlightAndOtherDetailsbyCa" +
            "rtItemIDResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(StayBazar.BookingServiceRef.InputException), Action="www.tamarindtours.in/IBookingService/IBookingService/GetFlightAndOtherDetailsbyCa" +
            "rtItemIDInputExceptionFault", Name="InputException", Namespace="http://schemas.datacontract.org/2004/07/TamarindXML.BusinessClass")]
        string GetFlightAndOtherDetailsbyCartItemID(StayBazar.BookingServiceRef.CartItemByID cart);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/IBookingService/IBookingService/GetFlightAndOtherDetailsbyCa" +
            "rtItemID", ReplyAction="www.tamarindtours.in/IBookingService/IBookingService/GetFlightAndOtherDetailsbyCa" +
            "rtItemIDResponse")]
        System.Threading.Tasks.Task<string> GetFlightAndOtherDetailsbyCartItemIDAsync(StayBazar.BookingServiceRef.CartItemByID cart);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/IBookingService/IBookingService/GetBookingList", ReplyAction="www.tamarindtours.in/IBookingService/IBookingService/GetBookingListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(StayBazar.BookingServiceRef.InputException), Action="www.tamarindtours.in/IBookingService/IBookingService/GetBookingListInputException" +
            "Fault", Name="InputException", Namespace="http://schemas.datacontract.org/2004/07/TamarindXML.BusinessClass")]
        string GetBookingList(StayBazar.BookingServiceRef.BookingList booklist);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/IBookingService/IBookingService/GetBookingList", ReplyAction="www.tamarindtours.in/IBookingService/IBookingService/GetBookingListResponse")]
        System.Threading.Tasks.Task<string> GetBookingListAsync(StayBazar.BookingServiceRef.BookingList booklist);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/IBookingService/IBookingService/ViewBookingHistory", ReplyAction="www.tamarindtours.in/IBookingService/IBookingService/ViewBookingHistoryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(StayBazar.BookingServiceRef.InputException), Action="www.tamarindtours.in/IBookingService/IBookingService/ViewBookingHistoryInputExcep" +
            "tionFault", Name="InputException", Namespace="http://schemas.datacontract.org/2004/07/TamarindXML.BusinessClass")]
        string ViewBookingHistory(StayBazar.BookingServiceRef.BookingDetails bkdetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/IBookingService/IBookingService/ViewBookingHistory", ReplyAction="www.tamarindtours.in/IBookingService/IBookingService/ViewBookingHistoryResponse")]
        System.Threading.Tasks.Task<string> ViewBookingHistoryAsync(StayBazar.BookingServiceRef.BookingDetails bkdetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/IBookingService/IBookingService/GetCancellationDetails", ReplyAction="www.tamarindtours.in/IBookingService/IBookingService/GetCancellationDetailsRespon" +
            "se")]
        string GetCancellationDetails(StayBazar.BookingServiceRef.Quotation quotation);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/IBookingService/IBookingService/GetCancellationDetails", ReplyAction="www.tamarindtours.in/IBookingService/IBookingService/GetCancellationDetailsRespon" +
            "se")]
        System.Threading.Tasks.Task<string> GetCancellationDetailsAsync(StayBazar.BookingServiceRef.Quotation quotation);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/IBookingService/IBookingService/CancelBooking", ReplyAction="www.tamarindtours.in/IBookingService/IBookingService/CancelBookingResponse")]
        string CancelBooking(StayBazar.BookingServiceRef.Quotation quotation);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/IBookingService/IBookingService/CancelBooking", ReplyAction="www.tamarindtours.in/IBookingService/IBookingService/CancelBookingResponse")]
        System.Threading.Tasks.Task<string> CancelBookingAsync(StayBazar.BookingServiceRef.Quotation quotation);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBookingServiceChannel : StayBazar.BookingServiceRef.IBookingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookingServiceClient : System.ServiceModel.ClientBase<StayBazar.BookingServiceRef.IBookingService>, StayBazar.BookingServiceRef.IBookingService {
        
        public BookingServiceClient() {
        }
        
        public BookingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetCartItemDetailsByCartItemID(StayBazar.BookingServiceRef.CartItemByID cartItem) {
            return base.Channel.GetCartItemDetailsByCartItemID(cartItem);
        }
        
        public System.Threading.Tasks.Task<string> GetCartItemDetailsByCartItemIDAsync(StayBazar.BookingServiceRef.CartItemByID cartItem) {
            return base.Channel.GetCartItemDetailsByCartItemIDAsync(cartItem);
        }
        
        public string InsertCartItem(StayBazar.BookingServiceRef.CartItem cartItem) {
            return base.Channel.InsertCartItem(cartItem);
        }
        
        public System.Threading.Tasks.Task<string> InsertCartItemAsync(StayBazar.BookingServiceRef.CartItem cartItem) {
            return base.Channel.InsertCartItemAsync(cartItem);
        }
        
        public string RemoveFromCart(StayBazar.BookingServiceRef.CartItemToDelete cartItem) {
            return base.Channel.RemoveFromCart(cartItem);
        }
        
        public System.Threading.Tasks.Task<string> RemoveFromCartAsync(StayBazar.BookingServiceRef.CartItemToDelete cartItem) {
            return base.Channel.RemoveFromCartAsync(cartItem);
        }
        
        public string GetCartDetails(StayBazar.BookingServiceRef.DetailedCart cart) {
            return base.Channel.GetCartDetails(cart);
        }
        
        public System.Threading.Tasks.Task<string> GetCartDetailsAsync(StayBazar.BookingServiceRef.DetailedCart cart) {
            return base.Channel.GetCartDetailsAsync(cart);
        }
        
        public string GetBookedCartDetails(StayBazar.BookingServiceRef.DetailedCart Cart) {
            return base.Channel.GetBookedCartDetails(Cart);
        }
        
        public System.Threading.Tasks.Task<string> GetBookedCartDetailsAsync(StayBazar.BookingServiceRef.DetailedCart Cart) {
            return base.Channel.GetBookedCartDetailsAsync(Cart);
        }
        
        public string GetSalutations() {
            return base.Channel.GetSalutations();
        }
        
        public System.Threading.Tasks.Task<string> GetSalutationsAsync() {
            return base.Channel.GetSalutationsAsync();
        }
        
        public string GetPolicies(StayBazar.BookingServiceRef.CartPolicies policy) {
            return base.Channel.GetPolicies(policy);
        }
        
        public System.Threading.Tasks.Task<string> GetPoliciesAsync(StayBazar.BookingServiceRef.CartPolicies policy) {
            return base.Channel.GetPoliciesAsync(policy);
        }
        
        public string ConfirmBooking(StayBazar.BookingServiceRef.Cart cart, StayBazar.BookingServiceRef.CartItemReferencePolicy[] CartItemRef) {
            return base.Channel.ConfirmBooking(cart, CartItemRef);
        }
        
        public System.Threading.Tasks.Task<string> ConfirmBookingAsync(StayBazar.BookingServiceRef.Cart cart, StayBazar.BookingServiceRef.CartItemReferencePolicy[] CartItemRef) {
            return base.Channel.ConfirmBookingAsync(cart, CartItemRef);
        }
        
        public string RejectApproval(StayBazar.BookingServiceRef.Quotation quot) {
            return base.Channel.RejectApproval(quot);
        }
        
        public System.Threading.Tasks.Task<string> RejectApprovalAsync(StayBazar.BookingServiceRef.Quotation quot) {
            return base.Channel.RejectApprovalAsync(quot);
        }
        
        public string AcceptApproval(StayBazar.BookingServiceRef.Quotation quot) {
            return base.Channel.AcceptApproval(quot);
        }
        
        public System.Threading.Tasks.Task<string> AcceptApprovalAsync(StayBazar.BookingServiceRef.Quotation quot) {
            return base.Channel.AcceptApprovalAsync(quot);
        }
        
        public string GetAmendBookingDetailsbyCartItemID(StayBazar.BookingServiceRef.CartItemByID cart) {
            return base.Channel.GetAmendBookingDetailsbyCartItemID(cart);
        }
        
        public System.Threading.Tasks.Task<string> GetAmendBookingDetailsbyCartItemIDAsync(StayBazar.BookingServiceRef.CartItemByID cart) {
            return base.Channel.GetAmendBookingDetailsbyCartItemIDAsync(cart);
        }
        
        public string GetFlightAndOtherDetailsbyCartItemID(StayBazar.BookingServiceRef.CartItemByID cart) {
            return base.Channel.GetFlightAndOtherDetailsbyCartItemID(cart);
        }
        
        public System.Threading.Tasks.Task<string> GetFlightAndOtherDetailsbyCartItemIDAsync(StayBazar.BookingServiceRef.CartItemByID cart) {
            return base.Channel.GetFlightAndOtherDetailsbyCartItemIDAsync(cart);
        }
        
        public string GetBookingList(StayBazar.BookingServiceRef.BookingList booklist) {
            return base.Channel.GetBookingList(booklist);
        }
        
        public System.Threading.Tasks.Task<string> GetBookingListAsync(StayBazar.BookingServiceRef.BookingList booklist) {
            return base.Channel.GetBookingListAsync(booklist);
        }
        
        public string ViewBookingHistory(StayBazar.BookingServiceRef.BookingDetails bkdetails) {
            return base.Channel.ViewBookingHistory(bkdetails);
        }
        
        public System.Threading.Tasks.Task<string> ViewBookingHistoryAsync(StayBazar.BookingServiceRef.BookingDetails bkdetails) {
            return base.Channel.ViewBookingHistoryAsync(bkdetails);
        }
        
        public string GetCancellationDetails(StayBazar.BookingServiceRef.Quotation quotation) {
            return base.Channel.GetCancellationDetails(quotation);
        }
        
        public System.Threading.Tasks.Task<string> GetCancellationDetailsAsync(StayBazar.BookingServiceRef.Quotation quotation) {
            return base.Channel.GetCancellationDetailsAsync(quotation);
        }
        
        public string CancelBooking(StayBazar.BookingServiceRef.Quotation quotation) {
            return base.Channel.CancelBooking(quotation);
        }
        
        public System.Threading.Tasks.Task<string> CancelBookingAsync(StayBazar.BookingServiceRef.Quotation quotation) {
            return base.Channel.CancelBookingAsync(quotation);
        }
    }
}
