//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelReport.TamarindBasic {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InputException", Namespace="http://schemas.datacontract.org/2004/07/TamarindXML.BusinessClass")]
    [System.SerializableAttribute()]
    public partial class InputException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InnerExceptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionMessage {
            get {
                return this.ExceptionMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionMessageField, value) != true)) {
                    this.ExceptionMessageField = value;
                    this.RaisePropertyChanged("ExceptionMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InnerException {
            get {
                return this.InnerExceptionField;
            }
            set {
                if ((object.ReferenceEquals(this.InnerExceptionField, value) != true)) {
                    this.InnerExceptionField = value;
                    this.RaisePropertyChanged("InnerException");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListHotelParam", Namespace="http://schemas.datacontract.org/2004/07/TamarindXML.BusinessClass")]
    [System.SerializableAttribute()]
    public partial class ListHotelParam : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StarRatingField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityID {
            get {
                return this.CityIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CityIDField, value) != true)) {
                    this.CityIDField = value;
                    this.RaisePropertyChanged("CityID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StarRating {
            get {
                return this.StarRatingField;
            }
            set {
                if ((object.ReferenceEquals(this.StarRatingField, value) != true)) {
                    this.StarRatingField = value;
                    this.RaisePropertyChanged("StarRating");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="www.tamarindtours.in/IBaseDetails", ConfigurationName="TamarindBasic.IBaseDetails")]
    public interface IBaseDetails {
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/IBaseDetails/IBaseDetails/GetDestinations", ReplyAction="www.tamarindtours.in/IBaseDetails/IBaseDetails/GetDestinationsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ExcelReport.TamarindBasic.InputException), Action="www.tamarindtours.in/IBaseDetails/IBaseDetails/GetDestinationsInputExceptionFault" +
            "", Name="InputException", Namespace="http://schemas.datacontract.org/2004/07/TamarindXML.BusinessClass")]
        string GetDestinations();
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/IBaseDetails/IBaseDetails/GetDestinations", ReplyAction="www.tamarindtours.in/IBaseDetails/IBaseDetails/GetDestinationsResponse")]
        System.Threading.Tasks.Task<string> GetDestinationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/IBaseDetails/IBaseDetails/GetCities", ReplyAction="www.tamarindtours.in/IBaseDetails/IBaseDetails/GetCitiesResponse")]
        string GetCities();
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/IBaseDetails/IBaseDetails/GetCities", ReplyAction="www.tamarindtours.in/IBaseDetails/IBaseDetails/GetCitiesResponse")]
        System.Threading.Tasks.Task<string> GetCitiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/IBaseDetails/IBaseDetails/GetHotelList", ReplyAction="www.tamarindtours.in/IBaseDetails/IBaseDetails/GetHotelListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ExcelReport.TamarindBasic.InputException), Action="www.tamarindtours.in/IBaseDetails/IBaseDetails/GetHotelListInputExceptionFault", Name="InputException", Namespace="http://schemas.datacontract.org/2004/07/TamarindXML.BusinessClass")]
        string GetHotelList(ExcelReport.TamarindBasic.ListHotelParam param);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/IBaseDetails/IBaseDetails/GetHotelList", ReplyAction="www.tamarindtours.in/IBaseDetails/IBaseDetails/GetHotelListResponse")]
        System.Threading.Tasks.Task<string> GetHotelListAsync(ExcelReport.TamarindBasic.ListHotelParam param);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/IBaseDetails/IBaseDetails/GetStarRatings", ReplyAction="www.tamarindtours.in/IBaseDetails/IBaseDetails/GetStarRatingsResponse")]
        string GetStarRatings();
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/IBaseDetails/IBaseDetails/GetStarRatings", ReplyAction="www.tamarindtours.in/IBaseDetails/IBaseDetails/GetStarRatingsResponse")]
        System.Threading.Tasks.Task<string> GetStarRatingsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/IBaseDetails/IBaseDetails/GetRoomTypes", ReplyAction="www.tamarindtours.in/IBaseDetails/IBaseDetails/GetRoomTypesResponse")]
        string GetRoomTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/IBaseDetails/IBaseDetails/GetRoomTypes", ReplyAction="www.tamarindtours.in/IBaseDetails/IBaseDetails/GetRoomTypesResponse")]
        System.Threading.Tasks.Task<string> GetRoomTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/IBaseDetails/IBaseDetails/GetDestinationDetails", ReplyAction="www.tamarindtours.in/IBaseDetails/IBaseDetails/GetDestinationDetailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ExcelReport.TamarindBasic.InputException), Action="www.tamarindtours.in/IBaseDetails/IBaseDetails/GetDestinationDetailsInputExceptio" +
            "nFault", Name="InputException", Namespace="http://schemas.datacontract.org/2004/07/TamarindXML.BusinessClass")]
        string GetDestinationDetails(ExcelReport.TamarindBasic.ListHotelParam param);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/IBaseDetails/IBaseDetails/GetDestinationDetails", ReplyAction="www.tamarindtours.in/IBaseDetails/IBaseDetails/GetDestinationDetailsResponse")]
        System.Threading.Tasks.Task<string> GetDestinationDetailsAsync(ExcelReport.TamarindBasic.ListHotelParam param);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/IBaseDetails/IBaseDetails/GetMasterCurrency", ReplyAction="www.tamarindtours.in/IBaseDetails/IBaseDetails/GetMasterCurrencyResponse")]
        string GetMasterCurrency();
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/IBaseDetails/IBaseDetails/GetMasterCurrency", ReplyAction="www.tamarindtours.in/IBaseDetails/IBaseDetails/GetMasterCurrencyResponse")]
        System.Threading.Tasks.Task<string> GetMasterCurrencyAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/IBaseDetails/IBaseDetails/GetCountries", ReplyAction="www.tamarindtours.in/IBaseDetails/IBaseDetails/GetCountriesResponse")]
        string GetCountries();
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/IBaseDetails/IBaseDetails/GetCountries", ReplyAction="www.tamarindtours.in/IBaseDetails/IBaseDetails/GetCountriesResponse")]
        System.Threading.Tasks.Task<string> GetCountriesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBaseDetailsChannel : ExcelReport.TamarindBasic.IBaseDetails, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BaseDetailsClient : System.ServiceModel.ClientBase<ExcelReport.TamarindBasic.IBaseDetails>, ExcelReport.TamarindBasic.IBaseDetails {
        
        public BaseDetailsClient() {
        }
        
        public BaseDetailsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BaseDetailsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BaseDetailsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BaseDetailsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetDestinations() {
            return base.Channel.GetDestinations();
        }
        
        public System.Threading.Tasks.Task<string> GetDestinationsAsync() {
            return base.Channel.GetDestinationsAsync();
        }
        
        public string GetCities() {
            return base.Channel.GetCities();
        }
        
        public System.Threading.Tasks.Task<string> GetCitiesAsync() {
            return base.Channel.GetCitiesAsync();
        }
        
        public string GetHotelList(ExcelReport.TamarindBasic.ListHotelParam param) {
            return base.Channel.GetHotelList(param);
        }
        
        public System.Threading.Tasks.Task<string> GetHotelListAsync(ExcelReport.TamarindBasic.ListHotelParam param) {
            return base.Channel.GetHotelListAsync(param);
        }
        
        public string GetStarRatings() {
            return base.Channel.GetStarRatings();
        }
        
        public System.Threading.Tasks.Task<string> GetStarRatingsAsync() {
            return base.Channel.GetStarRatingsAsync();
        }
        
        public string GetRoomTypes() {
            return base.Channel.GetRoomTypes();
        }
        
        public System.Threading.Tasks.Task<string> GetRoomTypesAsync() {
            return base.Channel.GetRoomTypesAsync();
        }
        
        public string GetDestinationDetails(ExcelReport.TamarindBasic.ListHotelParam param) {
            return base.Channel.GetDestinationDetails(param);
        }
        
        public System.Threading.Tasks.Task<string> GetDestinationDetailsAsync(ExcelReport.TamarindBasic.ListHotelParam param) {
            return base.Channel.GetDestinationDetailsAsync(param);
        }
        
        public string GetMasterCurrency() {
            return base.Channel.GetMasterCurrency();
        }
        
        public System.Threading.Tasks.Task<string> GetMasterCurrencyAsync() {
            return base.Channel.GetMasterCurrencyAsync();
        }
        
        public string GetCountries() {
            return base.Channel.GetCountries();
        }
        
        public System.Threading.Tasks.Task<string> GetCountriesAsync() {
            return base.Channel.GetCountriesAsync();
        }
    }
}
