//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelReport.Tamarind {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HotelSearchParam", Namespace="http://schemas.datacontract.org/2004/07/TamarindXML.BusinessClass")]
    [System.SerializableAttribute()]
    public partial class HotelSearchParam : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgentMarketField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AllowOnrequestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CheckinDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DoubleBedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExtraBedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HotelIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NightsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginCountryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SingleBedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TwinBedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgentMarket {
            get {
                return this.AgentMarketField;
            }
            set {
                if ((object.ReferenceEquals(this.AgentMarketField, value) != true)) {
                    this.AgentMarketField = value;
                    this.RaisePropertyChanged("AgentMarket");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowOnrequest {
            get {
                return this.AllowOnrequestField;
            }
            set {
                if ((this.AllowOnrequestField.Equals(value) != true)) {
                    this.AllowOnrequestField = value;
                    this.RaisePropertyChanged("AllowOnrequest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CheckinDate {
            get {
                return this.CheckinDateField;
            }
            set {
                if ((this.CheckinDateField.Equals(value) != true)) {
                    this.CheckinDateField = value;
                    this.RaisePropertyChanged("CheckinDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityID {
            get {
                return this.CityIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CityIDField, value) != true)) {
                    this.CityIDField = value;
                    this.RaisePropertyChanged("CityID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DoubleBed {
            get {
                return this.DoubleBedField;
            }
            set {
                if ((this.DoubleBedField.Equals(value) != true)) {
                    this.DoubleBedField = value;
                    this.RaisePropertyChanged("DoubleBed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExtraBed {
            get {
                return this.ExtraBedField;
            }
            set {
                if ((this.ExtraBedField.Equals(value) != true)) {
                    this.ExtraBedField = value;
                    this.RaisePropertyChanged("ExtraBed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HotelID {
            get {
                return this.HotelIDField;
            }
            set {
                if ((object.ReferenceEquals(this.HotelIDField, value) != true)) {
                    this.HotelIDField = value;
                    this.RaisePropertyChanged("HotelID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Nights {
            get {
                return this.NightsField;
            }
            set {
                if ((this.NightsField.Equals(value) != true)) {
                    this.NightsField = value;
                    this.RaisePropertyChanged("Nights");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginCountryID {
            get {
                return this.OriginCountryIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginCountryIDField, value) != true)) {
                    this.OriginCountryIDField = value;
                    this.RaisePropertyChanged("OriginCountryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rating {
            get {
                return this.RatingField;
            }
            set {
                if ((object.ReferenceEquals(this.RatingField, value) != true)) {
                    this.RatingField = value;
                    this.RaisePropertyChanged("Rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SingleBed {
            get {
                return this.SingleBedField;
            }
            set {
                if ((this.SingleBedField.Equals(value) != true)) {
                    this.SingleBedField = value;
                    this.RaisePropertyChanged("SingleBed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TwinBed {
            get {
                return this.TwinBedField;
            }
            set {
                if ((this.TwinBedField.Equals(value) != true)) {
                    this.TwinBedField = value;
                    this.RaisePropertyChanged("TwinBed");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InputException", Namespace="http://schemas.datacontract.org/2004/07/TamarindXML.BusinessClass")]
    [System.SerializableAttribute()]
    public partial class InputException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InnerExceptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionMessage {
            get {
                return this.ExceptionMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionMessageField, value) != true)) {
                    this.ExceptionMessageField = value;
                    this.RaisePropertyChanged("ExceptionMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InnerException {
            get {
                return this.InnerExceptionField;
            }
            set {
                if ((object.ReferenceEquals(this.InnerExceptionField, value) != true)) {
                    this.InnerExceptionField = value;
                    this.RaisePropertyChanged("InnerException");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SingleHotel", Namespace="http://schemas.datacontract.org/2004/07/TamarindXML.BusinessClass")]
    [System.SerializableAttribute()]
    public partial class SingleHotel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HotelIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HotelID {
            get {
                return this.HotelIDField;
            }
            set {
                if ((this.HotelIDField.Equals(value) != true)) {
                    this.HotelIDField = value;
                    this.RaisePropertyChanged("HotelID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CostBreakupParam", Namespace="http://schemas.datacontract.org/2004/07/TamarindXML.BusinessClass")]
    [System.SerializableAttribute()]
    public partial class CostBreakupParam : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CancellationDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CheckinDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DoubleBedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExtraBedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HotelRateCardDetailIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NightsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SingleBedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TwinBedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CancellationDetails {
            get {
                return this.CancellationDetailsField;
            }
            set {
                if ((this.CancellationDetailsField.Equals(value) != true)) {
                    this.CancellationDetailsField = value;
                    this.RaisePropertyChanged("CancellationDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CheckinDate {
            get {
                return this.CheckinDateField;
            }
            set {
                if ((this.CheckinDateField.Equals(value) != true)) {
                    this.CheckinDateField = value;
                    this.RaisePropertyChanged("CheckinDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DoubleBed {
            get {
                return this.DoubleBedField;
            }
            set {
                if ((this.DoubleBedField.Equals(value) != true)) {
                    this.DoubleBedField = value;
                    this.RaisePropertyChanged("DoubleBed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExtraBed {
            get {
                return this.ExtraBedField;
            }
            set {
                if ((this.ExtraBedField.Equals(value) != true)) {
                    this.ExtraBedField = value;
                    this.RaisePropertyChanged("ExtraBed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HotelRateCardDetailID {
            get {
                return this.HotelRateCardDetailIDField;
            }
            set {
                if ((object.ReferenceEquals(this.HotelRateCardDetailIDField, value) != true)) {
                    this.HotelRateCardDetailIDField = value;
                    this.RaisePropertyChanged("HotelRateCardDetailID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Nights {
            get {
                return this.NightsField;
            }
            set {
                if ((this.NightsField.Equals(value) != true)) {
                    this.NightsField = value;
                    this.RaisePropertyChanged("Nights");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SingleBed {
            get {
                return this.SingleBedField;
            }
            set {
                if ((this.SingleBedField.Equals(value) != true)) {
                    this.SingleBedField = value;
                    this.RaisePropertyChanged("SingleBed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TwinBed {
            get {
                return this.TwinBedField;
            }
            set {
                if ((this.TwinBedField.Equals(value) != true)) {
                    this.TwinBedField = value;
                    this.RaisePropertyChanged("TwinBed");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Quotation", Namespace="http://schemas.datacontract.org/2004/07/TamarindXML.BusinessClass")]
    [System.SerializableAttribute()]
    public partial class Quotation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CancellationDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuotationIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CancellationDetails {
            get {
                return this.CancellationDetailsField;
            }
            set {
                if ((this.CancellationDetailsField.Equals(value) != true)) {
                    this.CancellationDetailsField = value;
                    this.RaisePropertyChanged("CancellationDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QuotationID {
            get {
                return this.QuotationIDField;
            }
            set {
                if ((this.QuotationIDField.Equals(value) != true)) {
                    this.QuotationIDField = value;
                    this.RaisePropertyChanged("QuotationID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CancellationPolicyParam", Namespace="http://schemas.datacontract.org/2004/07/TamarindXML.BusinessClass")]
    [System.SerializableAttribute()]
    public partial class CancellationPolicyParam : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CancellationDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CheckinDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HotelRateCardDetailIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CancellationDetails {
            get {
                return this.CancellationDetailsField;
            }
            set {
                if ((this.CancellationDetailsField.Equals(value) != true)) {
                    this.CancellationDetailsField = value;
                    this.RaisePropertyChanged("CancellationDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CheckinDate {
            get {
                return this.CheckinDateField;
            }
            set {
                if ((this.CheckinDateField.Equals(value) != true)) {
                    this.CheckinDateField = value;
                    this.RaisePropertyChanged("CheckinDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HotelRateCardDetailID {
            get {
                return this.HotelRateCardDetailIDField;
            }
            set {
                if ((object.ReferenceEquals(this.HotelRateCardDetailIDField, value) != true)) {
                    this.HotelRateCardDetailIDField = value;
                    this.RaisePropertyChanged("HotelRateCardDetailID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="www.tamarindtours.in/ITamarindDataService", ConfigurationName="Tamarind.ITamarindDataService")]
    public interface ITamarindDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/ITamarindDataService/ITamarindDataService/SearchHotels", ReplyAction="www.tamarindtours.in/ITamarindDataService/ITamarindDataService/SearchHotelsRespon" +
            "se")]
        [System.ServiceModel.FaultContractAttribute(typeof(ExcelReport.Tamarind.InputException), Action="www.tamarindtours.in/ITamarindDataService/ITamarindDataService/SearchHotelsInputE" +
            "xceptionFault", Name="InputException", Namespace="http://schemas.datacontract.org/2004/07/TamarindXML.BusinessClass")]
        string SearchHotels(ExcelReport.Tamarind.HotelSearchParam param);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/ITamarindDataService/ITamarindDataService/SearchHotels", ReplyAction="www.tamarindtours.in/ITamarindDataService/ITamarindDataService/SearchHotelsRespon" +
            "se")]
        System.Threading.Tasks.Task<string> SearchHotelsAsync(ExcelReport.Tamarind.HotelSearchParam param);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/ITamarindDataService/ITamarindDataService/GetHotels", ReplyAction="www.tamarindtours.in/ITamarindDataService/ITamarindDataService/GetHotelsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ExcelReport.Tamarind.InputException), Action="www.tamarindtours.in/ITamarindDataService/ITamarindDataService/GetHotelsInputExce" +
            "ptionFault", Name="InputException", Namespace="http://schemas.datacontract.org/2004/07/TamarindXML.BusinessClass")]
        string GetHotels(ExcelReport.Tamarind.HotelSearchParam param);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/ITamarindDataService/ITamarindDataService/GetHotels", ReplyAction="www.tamarindtours.in/ITamarindDataService/ITamarindDataService/GetHotelsResponse")]
        System.Threading.Tasks.Task<string> GetHotelsAsync(ExcelReport.Tamarind.HotelSearchParam param);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/ITamarindDataService/ITamarindDataService/GetHotelInfo", ReplyAction="www.tamarindtours.in/ITamarindDataService/ITamarindDataService/GetHotelInfoRespon" +
            "se")]
        [System.ServiceModel.FaultContractAttribute(typeof(ExcelReport.Tamarind.InputException), Action="www.tamarindtours.in/ITamarindDataService/ITamarindDataService/GetHotelInfoInputE" +
            "xceptionFault", Name="InputException", Namespace="http://schemas.datacontract.org/2004/07/TamarindXML.BusinessClass")]
        string GetHotelInfo(ExcelReport.Tamarind.SingleHotel hotel);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/ITamarindDataService/ITamarindDataService/GetHotelInfo", ReplyAction="www.tamarindtours.in/ITamarindDataService/ITamarindDataService/GetHotelInfoRespon" +
            "se")]
        System.Threading.Tasks.Task<string> GetHotelInfoAsync(ExcelReport.Tamarind.SingleHotel hotel);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/ITamarindDataService/ITamarindDataService/GetCostBreakup", ReplyAction="www.tamarindtours.in/ITamarindDataService/ITamarindDataService/GetCostBreakupResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ExcelReport.Tamarind.InputException), Action="www.tamarindtours.in/ITamarindDataService/ITamarindDataService/GetCostBreakupInpu" +
            "tExceptionFault", Name="InputException", Namespace="http://schemas.datacontract.org/2004/07/TamarindXML.BusinessClass")]
        string GetCostBreakup(ExcelReport.Tamarind.CostBreakupParam brkupParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/ITamarindDataService/ITamarindDataService/GetCostBreakup", ReplyAction="www.tamarindtours.in/ITamarindDataService/ITamarindDataService/GetCostBreakupResp" +
            "onse")]
        System.Threading.Tasks.Task<string> GetCostBreakupAsync(ExcelReport.Tamarind.CostBreakupParam brkupParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/ITamarindDataService/ITamarindDataService/viewPendingApprova" +
            "ls", ReplyAction="www.tamarindtours.in/ITamarindDataService/ITamarindDataService/viewPendingApprova" +
            "lsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ExcelReport.Tamarind.InputException), Action="www.tamarindtours.in/ITamarindDataService/ITamarindDataService/viewPendingApprova" +
            "lsInputExceptionFault", Name="InputException", Namespace="http://schemas.datacontract.org/2004/07/TamarindXML.BusinessClass")]
        string viewPendingApprovals();
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/ITamarindDataService/ITamarindDataService/viewPendingApprova" +
            "ls", ReplyAction="www.tamarindtours.in/ITamarindDataService/ITamarindDataService/viewPendingApprova" +
            "lsResponse")]
        System.Threading.Tasks.Task<string> viewPendingApprovalsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/ITamarindDataService/ITamarindDataService/approvalreject", ReplyAction="www.tamarindtours.in/ITamarindDataService/ITamarindDataService/approvalrejectResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ExcelReport.Tamarind.InputException), Action="www.tamarindtours.in/ITamarindDataService/ITamarindDataService/approvalrejectInpu" +
            "tExceptionFault", Name="InputException", Namespace="http://schemas.datacontract.org/2004/07/TamarindXML.BusinessClass")]
        string approvalreject(ExcelReport.Tamarind.Quotation app);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/ITamarindDataService/ITamarindDataService/approvalreject", ReplyAction="www.tamarindtours.in/ITamarindDataService/ITamarindDataService/approvalrejectResp" +
            "onse")]
        System.Threading.Tasks.Task<string> approvalrejectAsync(ExcelReport.Tamarind.Quotation app);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/ITamarindDataService/ITamarindDataService/GetCancellationPol" +
            "icies", ReplyAction="www.tamarindtours.in/ITamarindDataService/ITamarindDataService/GetCancellationPol" +
            "iciesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ExcelReport.Tamarind.InputException), Action="www.tamarindtours.in/ITamarindDataService/ITamarindDataService/GetCancellationPol" +
            "iciesInputExceptionFault", Name="InputException", Namespace="http://schemas.datacontract.org/2004/07/TamarindXML.BusinessClass")]
        string GetCancellationPolicies(ExcelReport.Tamarind.CancellationPolicyParam CancellationPolicy);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.tamarindtours.in/ITamarindDataService/ITamarindDataService/GetCancellationPol" +
            "icies", ReplyAction="www.tamarindtours.in/ITamarindDataService/ITamarindDataService/GetCancellationPol" +
            "iciesResponse")]
        System.Threading.Tasks.Task<string> GetCancellationPoliciesAsync(ExcelReport.Tamarind.CancellationPolicyParam CancellationPolicy);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITamarindDataServiceChannel : ExcelReport.Tamarind.ITamarindDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TamarindDataServiceClient : System.ServiceModel.ClientBase<ExcelReport.Tamarind.ITamarindDataService>, ExcelReport.Tamarind.ITamarindDataService {
        
        public TamarindDataServiceClient() {
        }
        
        public TamarindDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TamarindDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TamarindDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TamarindDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SearchHotels(ExcelReport.Tamarind.HotelSearchParam param) {
            return base.Channel.SearchHotels(param);
        }
        
        public System.Threading.Tasks.Task<string> SearchHotelsAsync(ExcelReport.Tamarind.HotelSearchParam param) {
            return base.Channel.SearchHotelsAsync(param);
        }
        
        public string GetHotels(ExcelReport.Tamarind.HotelSearchParam param) {
            return base.Channel.GetHotels(param);
        }
        
        public System.Threading.Tasks.Task<string> GetHotelsAsync(ExcelReport.Tamarind.HotelSearchParam param) {
            return base.Channel.GetHotelsAsync(param);
        }
        
        public string GetHotelInfo(ExcelReport.Tamarind.SingleHotel hotel) {
            return base.Channel.GetHotelInfo(hotel);
        }
        
        public System.Threading.Tasks.Task<string> GetHotelInfoAsync(ExcelReport.Tamarind.SingleHotel hotel) {
            return base.Channel.GetHotelInfoAsync(hotel);
        }
        
        public string GetCostBreakup(ExcelReport.Tamarind.CostBreakupParam brkupParam) {
            return base.Channel.GetCostBreakup(brkupParam);
        }
        
        public System.Threading.Tasks.Task<string> GetCostBreakupAsync(ExcelReport.Tamarind.CostBreakupParam brkupParam) {
            return base.Channel.GetCostBreakupAsync(brkupParam);
        }
        
        public string viewPendingApprovals() {
            return base.Channel.viewPendingApprovals();
        }
        
        public System.Threading.Tasks.Task<string> viewPendingApprovalsAsync() {
            return base.Channel.viewPendingApprovalsAsync();
        }
        
        public string approvalreject(ExcelReport.Tamarind.Quotation app) {
            return base.Channel.approvalreject(app);
        }
        
        public System.Threading.Tasks.Task<string> approvalrejectAsync(ExcelReport.Tamarind.Quotation app) {
            return base.Channel.approvalrejectAsync(app);
        }
        
        public string GetCancellationPolicies(ExcelReport.Tamarind.CancellationPolicyParam CancellationPolicy) {
            return base.Channel.GetCancellationPolicies(CancellationPolicy);
        }
        
        public System.Threading.Tasks.Task<string> GetCancellationPoliciesAsync(ExcelReport.Tamarind.CancellationPolicyParam CancellationPolicy) {
            return base.Channel.GetCancellationPoliciesAsync(CancellationPolicy);
        }
    }
}
